### ISSUE TITLE
run-errors

### ISSUE THREAD

**Issue by lijiajun520** [jmiemirza/Meta-Prompting#1]
When I am running “bash scripts/zero_shot.sh mpvr gpt clip_b32 eurosat imagenet_r” , the following error appears. How can I download or train the missing one?
FileNotFoundError: [Errno 2] No such file or directory: './descriptions/mixtral/DescribableTextures.json'

**Comment by jmiemirza** [comment]
Hi, 

Thanks for your interest. Please follow the readme to get the data and run the experiments. All details are present there. 

Best,
